version: "3"

services:
  wallet:
    build: .
    command: ./bin/server serve
    ports: 
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

